### ISSUE TITLE
Enabling Disk accessed based walk generation

### ISSUE THREAD

**Issue by redadmiral** [dwslab/jRDF2Vec#3]
Hi Jan,
thank you very much for re-implementing the rdf2vec algorithm! I tried it on a small graph for testing and it worked like a charm :sparkles: 

Now I want to generate vectors out of a ~100 GB .nt file and my machine's running out of memory. You write in the intro that disk access based walk generation is also possible. How can I enable this feature? From the naming convention of your modules I suppose I have to generate a .hdt file – is this the case?

Thank you very much for your help in advance!

**Comment by janothan** [comment]
Hi redadmiral! Sorry for the late reply.
Yes, the NT Parser currently loads everything into memory so for 100GB you need quite some RAM.

Yes! I suggest you use HDT for now. 
The walk generation will be significantly slower though.
