### ISSUE TITLE
what does this warning means i dont get it

### ISSUE THREAD

**Issue by WarisBunglawala** [dwslab/jRDF2Vec#93]
while generating walks with embedText for all nt file in dir

``nohup java -Xmx75g -jar jrdf2vec-1.2-SNAPSHOT.jar -graph <nt file dir> -embedText -onlyWalks &``

Using server port: 1808
Using 20 threads for walk generation and training.
Using depth 4
Generating 100 walks per entity.
Only walks are being generated, training is performed.
23 Feb 2022 13:06:47  WARN [main] (WalkGenerationManager.java:179) - You specified a directory. Trying to parse files in the directory. The program will fail (later) if you use an entity selector that requires one ontology.

what does program will fail later if you use an entity selcetor that requires one ontology means ?

**Comment by janothan** [comment]
You can ignore this warning. I will set the log level for this message to `debug`. It is an implementation specific remark.
It comes down to the fact that some configurations will not work (but the plain vanilla case works).

Just FYI `-embedText` is really an experimental feature. I have neither evaluated this in depth nor published on text-based RDF2vec variants. I recommend the default case (no text) if you do not need text.
